# Generated by Django 4.1.1 on 2022-09-19 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Governor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        help_text="Enter governors first name",
                        max_length=100,
                        verbose_name="first name",
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        help_text="Enter governors last name",
                        max_length=100,
                        verbose_name="last name",
                    ),
                ),
                (
                    "other_names",
                    models.CharField(
                        blank=True,
                        help_text="Enter governors other names",
                        max_length=100,
                        verbose_name="other_names",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True,
                        help_text="Known address of the governor.",
                        max_length=200,
                        verbose_name="address",
                    ),
                ),
                ("started", models.DateTimeField()),
                ("ended", models.DateTimeField()),
            ],
        ),
    ]
